# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
- group: EHR Alpha

stages:
- stage: Build
  displayName: Build and upgrade database
  jobs:
  - job: Build
    displayName: Build and Upgrade
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: replacetokens@3
      displayName: Replace settings
      inputs:
        tokenPrefix: '$('
        tokenSuffix: ')'
        targetFiles: pom.xml
    - task: Maven@3
      enabled: true
         
